[package]
name = "frankasend"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello = "1.0.4"
local-ip-address = "0.5.6"
